//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celular
    {
        public Celular()
        {
            this.Proposta = new HashSet<Proposta>();
        }
    
        public int idCelular { get; set; }
        public int idPessoa { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string estadoFisico { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<Proposta> Proposta { get; set; }
    }
}
