//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int idEndereco { get; set; }
        public int idPessoa { get; set; }
        public string cep { get; set; }
        public string bairro { get; set; }
        public string rua { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
