//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaFisica
    {
        public int idPessoa { get; set; }
        public long cpf { get; set; }
        public string sexo { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string NumeroCasa { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
