//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelaWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposta
    {
        public int idProposta { get; set; }
        public int idPessoaJuridica { get; set; }
        public int idCelular { get; set; }
        public decimal valor { get; set; }
        public System.DateTime date { get; set; }
        public int horario { get; set; }
        public string status { get; set; }
    
        public virtual Celular Celular { get; set; }
        public virtual PessoaJuridica PessoaJuridica { get; set; }
    }
}
